# Acknowledgements {.unnumbered}

We have very many people to thank for their intellectual companionship as we wrote and rewrote this book.

We finished a first  draft of the manuscript during a year together in Berlin and held a book conference in May 2017, at a time when we reckoned that we were more or less done.   Huge thanks to Stefanie Roth, Marion Obermaier, and  Ina Thies-Hoelzmann for organizing this workshop and  to Dorothea Kübler for so generously hosting us that year.   We are grateful to participants at the workshop Jeyhun Alizade, Andrew Bennett (joining at impossible hours), Sebastian Bödeker, Kevin Clarke,  Ruth Ditlmann, Tulia Falleti, Adam Glynn, Alexandra Hartman, Jan Paul Heisig, Michael C. Herron, Nahomi Ichino, Mark Kayser, Johannes Leutgeb, Anselm Rink, Ingo Rohlfing, Nicholas Weller, and Sherry Zaks for stimulating conversations that made us rethink many aspects of the project. Collectively you set us back about five years.

As we rethought and rewrote the book, we continued to benefit from generous engagements from these and other friends and colleagues. We received very helpful feedback at a 2019 authors' workshop at the Institute for Qualitative and Multi-Method Research (IQMR) at Syracuse University, especially from Michael Findley, John Gerring, and Jason Seawright. At the WZB, colleagues in the causality project joined us in grappling with many of the core ideas; thanks especially to Michael Zürn, Steffen Huck, Johannes Leutgeb and Julio Solis Arce for their insights. Other colleagues, often coming from quite different intellectual traditions, engaged us us on many aspects of the approach as we refined the manuscript. We benefited greatly from one-on-one exchanges with P.M. Aronow, Tim Frye, Donald Green, John Huber, Thomas Leavitt, Winston Lin, Richard Nielsen, and Fredrik Sävje. Multiple in-depth discussions with Tasha Fairfield and Andrew Charman over the years helped us understand key points of difference between their approach and ours and sharpened our thinking.  Conversations  Laura Garcia-Montoya and James Mahoney challenged on us ways to think about causal relations. Collaboration with members of the POInT team---Calum Davey, Matt Juden, Elizabeth Allen, Lily Medina, Henry Mwambi, Audrey Prost, and Rachel Sarguta---on applications of the `CausalQueries` package to a set of development studies advanced our thinking about practical uses of the approach. Seminar audiences at the Technical University of Munich, the University of Rochester, Northwestern, and Yale pointed us to conceptual ambiguities in the framework that needed  work.

Nothing helps clarify ideas more than having to teach them, and the book has been taught now at multiple summer schools. Macartan thanks participants at EITM 2017 in Milan who bravely worked with the earliest version of `CausalQueries`. Alan is grateful for the sharp and tough questions and the insightful suggestions from numerous cohorts of graduate students and junior faculty in the causal models module that he and Lily Medina taught at IQMR and at EITM in Ann Arbor.

Many others provided wonderful technical support and provided  fresh reactions to the ideas developed in the book. Daniel Markovits prepped the data for the institutions and growth analysis and also ran and wrote up all the initial analyses using that data. Big thanks to you for taking that so far.
Yonel Admasu prepped the data for for the democratization model analysis in @sec-HJC16; thanks for the careful scouting of multiple literatures.

Huge thanks to Manu Singh, one of the few to have read the whole book as it neared completion. Thanks for the careful read, the many improvements to the writing, and your insights on where weaknesses remained.  Warm thanks to Beatrice Montano and Vartika Savarna too, for your careful reading and wonderful feedback. And our deepest gratitude to Sampada KC for your meticulous work constructing the book’s index.

Our thinking in the book grew alongside the development of the accompanying `R` package, `CausalQueries`. Many  talented people contributed to developing the package and we owe them a lot. Jasper Cooper and  Georgiy Syunyaev cracked some of the earliest challenges, Lily Medina developed the guts of the package, and she and  Till Tietz saw it safely to CRAN. Clara Bicalho, Jonah Foong, Merlin Heidemanns, and Julio Solis Arce, contributed innumerable improvements. Julian Cantor got deep into the weeds on figuring out probabilities of new data patterns after case selection. 	Till Tietz dug deep to add elegance and speed. Sisi Huang developed a whole shiny application for the package and, as an early user, pointed to innumerable areas for improvement. Ben Goodrich gave us guidance on handling `stan` that was of huge consequence.

John Haslam at Cambridge has been a paragon of patience and a constant support at a distance. We are grateful to the *Strategies for Social Inquiry* series editors, Colin Elman, John Gerring, and James Mahoney, for letting us know early on that they thought this would be a book worth writing; the prospect of having this work appear in their great series has been a big motivation for us throughout. Our anonymous reviewer at Cambridge, Andrew Bennett, sent in 20 single-spaced pages of detailed, thoughtful, and incredibly constructive comments. You couldn't wish it on anyone.  

Thanks to the Alexander von Humboldt Foundation and the Social Sciences and Humanities Research Council of Canada for financial support for many aspects of the project.

Thank you, last, to our families for your support throughout this project, especially through a string of trans-Atlantic trips to “finish the book." Now we've really done it.


